version: '3.8'

services:
  # Servicio de la aplicación Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shinego_app
    volumes:
      - .:/var/www/html:delegated
    networks:
      - shinego_network
    depends_on:
      - db
    command: ["php-fpm", "-F"]
    env_file: .env

  # Servicio de Nginx para servir la aplicación Laravel
  webserver:
    image: nginx:alpine
    container_name: shinego_nginx
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-bot.conf:/etc/nginx/conf.d/nginx-bot.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "8000:80"
      - "443:443"
    networks:
      - shinego_network
    depends_on:
      - app

  # Servicio de MySQL
  db:
    image: mysql:8.0
    container_name: shinygo_db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: ShinyGo
      MYSQL_USER: shinygo_user
      MYSQL_PASSWORD: admin123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - shinego_network

  # Servicio de Certbot para obtener certificados SSL
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - .:/var/www/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - shinego_network

networks:
  shinego_network:
    driver: bridge

volumes:
  db_data:

